myPortfolio/urls.py
from django.contrib import admin
from django.urls import include, path
import portfolio.views as views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portfolio/', include('portfolio.urls')),
    path('', views.index)
]

portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('experience/', views.ExperienceView.as_view(), name='experience'),
    path('extraCurriculum/', views.ExtraCurriculumView.as_view(), name='extraCurriculum'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

portfolio/models.py
from django.db import models


class Comment(models.Model):

    subject = models.CharField(max_length= 100)

    email = models.CharField(max_length=100)

    comment = models.TextField( max_length=256)

    def __str__(self):
        return self.comment

portfolio/forms.py
from django import forms
from portfolio.models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        widgets = {
            'subject': forms.Textarea(
                attrs={
                    'id': 'subject',
                    'style' : 'height: 40px; font-size: 18px; resize: none; display: inline;',
                    'class' : 'col-12 mt-2 p-2 d-flex justify-content-center',
                }
            ),
            'email':forms.Textarea(
                attrs={
                    'id': 'email',
                    'style' : 'height: 40px; font-size: 18px; resize: none; display: inline;',
                    'class' : 'col-12 mt-2 p-2 d-flex justify-content-center',
                }
            ),
            'comment':forms.Textarea(
                attrs={
                    'id': 'comment',
                    'style' : 'height: 250px; font-size: 18px; border-radius: 1rem;',
                    'class' : 'col-12 mt-2 p-3 d-flex justify-content-center',
                }
            )
        }

portfolio/views.py
from random import sample
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import FormView
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models.functions import Lower

from .forms import CommentForm
from .models import Comment
import logging

def index(request):
    #redirect user to the polls index
    return HttpResponseRedirect(reverse("portfolio:index"))


class IndexView(generic.ListView):
    template_name = 'portfolio/index.html'

    def get_queryset(self):
        """
        Redirect to the home page
        """
        return Comment

class ExperienceView(generic.ListView):
    template_name = 'portfolio/experience.html'
    model = Comment
    def get_queryset(self):
        """
        Redirect to the experience page
        """
        return Comment


class ExtraCurriculumView(generic.ListView):
    template_name = 'portfolio/extraCurriculum.html'
    model = Comment
    def get_queryset(self):
        """
        Redirect to the extra curriculum page
        """
        return Comment

class ContactView(FormView):
    template_name = 'portfolio/contact.html'
    form_class = CommentForm
        
    def post(self, request, *args, **kwargs):
        """
        Redirect to the contact page with a form 
        """
        print("Post") 
        form = self.form_class(request.POST) 
        if form.is_valid():
            form.save()
            return render(request, 'portfolio/thanks.html', {'form': form})

portfolio/templates/portfolio/base.html
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com"> 
    <link rel="preconnect" href="https://fonts.gstatic.com"> 
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'portfolio/base.css' %}">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark"  style="background-color:#fadd34">
        <div class="container-fluid">
        <a style="margin-left:5rem" class="navbar-brand" href="#">My Profile</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ml-auto mt-auto">
                    <div class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'portfolio:index' %}">Home</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'portfolio:experience' %}">Experiences</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'portfolio:extraCurriculum' %}">Extra Curriculum</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'portfolio:contact' %}">Contact Me</a>
                        </li>
                    </div>  
                </div>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

portfolio/templates/portfolio/contact.html
{% extends "portfolio/base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/contact.css' %}">

<div class="container p-4">
    <div class="col pt-3">
        <div class="row">
        <h1>Contact Me</h1>
        </div>
        <div class="row mt-2">
            <div class="contact col-3 m-3">
                <h4>Phone Number</h4>
                <h5>(+66)626291556</h5>  

                <h4 style="margin-top:1rem">Email</h4>
                <h5>jitta.k@ku.th</h5>  

                <h4 style="margin-top:1rem">Github ID</h4>
                <h5>github.com/jittaearn </h5>  

                <h4 style="margin-top:1rem">Address</h4>
                <h5>
                    37 BB Apartment PHAHOLYOTHIN
                    24 KWANG JOMPOL KHET JATUCHAK BANGKOK 10900 THAILAND
                </h5> 
            </div> 
            <div class="col">
                <div class="container">
                    <form method="POST">
                    <fieldset>
                        <legend>Tell me what you think about this portfolio application!!</legend>
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="sumbit btn btn-dark">Submit</button>
                    </fieldset>
                    </form>
                </div>
            </div>
        </div>  
    </div>
</div>
{% endblock %}

portfolio/templates/portfolio/experience.html
{% extends "portfolio/base.html" %}
{% block content %}
{% load static %}

    <link rel="stylesheet" href="{% static 'portfolio/experience.css' %}">

    <div class="container p-3">
        <div class="col">
            <div class="row">
                <h1>Experiences</h1>
            </div>
            <div class="row">
                <div class="exbox col m-3">
                    <h2>ACADEMIC HISTORY</h2>
                    <br>
                    <h3>YFU Exchange Program USA</h3>
                    <h4>Gateway Legacy Christian</h4>
                    <h4>Academy School</h4>  
                    <h5>GPA (4.14/4.00)</h5>  
                    <h6>| 2015 - 2016</h6>  
                    <br>
                    <h3>SCIENCE MATHEMATICS PROGRAM</h3>
                    <h4>Saint John Mary</h4>  
                    <h4>International School</h4>  
                    <h5>GPA (3.88/4.00)</h5>  
                    <h6>| 2016 - 2018</h6> 
                    <br>
                    <h3>SOFTWARE & KNOWLEDGE</h3>
                    <h3>ENGINEERING</h3>
                    <h4>Gateway Legacy Christian</h4>  
                    <h4>Academy School</h4>  
                    <h5>GPA (2.91/4.00)</h5>  
                    <h6>| 2018 - Present</h6> 
                </div>  
                <div class="col m-3">
                    <div class="exbox row">
                        <h2>EXPERIENCES</h2>
                        <h3>EXCEED CAMP 16th</h3>
                        <h4>At Kasetsart University</h4>  
                        <h5>Software Training Camp</h5>
                        <h6>| JUL 2019</h6>    
                        <br>
                        <br>
                        <h3>INTERNSHIP</h3>
                        <h4>At In360 Co., Ltd.</h4>  
                        <h5>Team Development (ITD)</h5> 
                        <h6>| JUL 2020</h6>     
                    </div> 
                    <br>
                    <div class="exbox row">
                        <h2>INDIVIDUAL PROJECTS</h2>
                        <br>
                        <h3>CANDYHOUSE</h3>
                        <h4>A 2D platform games create with Python and Arcade library</h4>  
                        <h5>Arcade Game</h5>  
                        <h6>| MAY 2019</h6> 
                    </div>  
                </div>
                <div class="col m-3">
                    <div class="exbox row">
                        <h2>GROUP PROJECTS</h2>
                        <br>
                        <h3>SLEEP_WALKING</h3> 
                        <h4>Collect, analyse and signals from sensor for 
                            sleep walking patients and display on website</h4>  
                        <h5>IoT Website</h5>
                        <h6>| JUL 2019</h6>  
                        <br>
                        <br>
                        <h3>THOR</h3>  
                        <h4>An online games using Django framework and MySQL Database. </h4>  
                        <h5>Game Application</h5>
                        <h6>| DEC 2019</h6> 
                    </div> 
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

portfolio/templates/portfolio/extraCurriculum.html
{% extends "portfolio/base.html" %}
{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/extra.css' %}">


    <div class="container p-4">
        <div class="col">
            <div class="row">
                <h1>Extra Curriculum</h1>
            </div>
            <div class="row">
                <div class="col-4 m-3">
                    <div class="exbox row">
                        <h2>Academic Experiences</h2>
                        <h3>ENGINEERING SERVICE 30</h3>
                        <h4>Teach Math to M.6 Students</h4> 
                        <h5>Partial Fraction</h5>  
                        <h6>| JUN-JUL 2019</h6>  
                        <img src="{% static 'portfolio/images/2.jpg' %}" alt="es30 picture">
                        <h3>PEE SORN NONG</h3>
                        <h4>Teach Math to Freshmen Year</h4>  
                        <h5>Teach and TA</h5>  
                        <h6>| JUN 2020</h6> 
                        <img src="{% static 'portfolio/images/1.jpg' %}" alt="Pee sorn nong picture">
                    </div>
                </div>  
                <div class="col-4 m-3">
                    <div class="exbox row">
                        <h2>Hobbies</h2>
                        <h5>I love WATCHING MOVIES and SERIES Along with Playing Games such as Dota2 and ROV</h5>
                        <h3>I also enjoyed EXERCISING whenever I have the time. I usually run, and do some cardio workout</h3>
                        <h6>| 24 NOV 2020</h6> 
                        <img src="{% static 'portfolio/images/run.jpg' %}" alt="run picture">
                    </div> 
                </div>
                <div class="col-3 m-3">
                    <div class="exbox row">
                    <h2>Activities</h2>
                    <h3>SOS Staff</h3>
                    <h4>Prepare and organize the SOS Camp</h4>  
                    <h5>CAMERA MAN</h5>  
                    <h6>| JUL 2019</h6> 
                    <img src="{% static 'portfolio/images/sos.jpg' %}" alt="sos picture">
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

portfolio/templates/portfolio/index.html
{% extends "portfolio/base.html" %}
{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/index.css' %}">
    <div class="container p-4">
        <div class="col pt-3">
            <div class="row">
            <h1>Jitta Koopratoomsiri</h1>
            </div>
            <div class="row mt-2">
                <div class="col-7 m-3">
                    <h3>SOFTWARE DEVELOPER</h3>
                    <p style="padding-top: 1rem"> 
                    Hello, my name is Earn. Currently, a third-year Software & Knowledge Engineering student 
                    at Kasetsart University. I am interested in software development, and I enjoyed working on 
                    FrontEnd development. Nevertheless, I am eager to work more on BackEnd development and data analysis.
                    </p>
                    <div class="row mt-1">
                        <div class="col-4">
                            <h4>PROGRAMMING LANGUAGES</h4>
                            <h5>Python, JavaScript</h5>  
                        </div>
                        <div class="col-5">
                            <br>
                            <h4>WEBSITE DEVELOPMENT</h4>
                            <h5>HTML, CSS, PYTHON DJANGO</h5>  
                        </div>
                        <div class="col-3">
                            <br>
                            <h4>DATABASE</h4>
                            <h5>SQL Queries</h5>  
                        </div>
                    </div>
                    <div class="row mt-1">
                        <div class="col">
                            <h4>Soft Skills</h4>
                            <h5>Motivated, Adaptive, Team-player </h5>    
                        </div>
                        <div class="col">
                        <br>
                            <div class="row mt-2">
                                <h4>LANGUAGES</h4>
                                <div class="col">
                                    <h5>Thai Native</h5>
                                </div> 
                                <div class="col">
                                    <h5>English Proficient</h5>
                                </div>  
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col m-3">
                    <img src="{% static 'portfolio/images/profile.jpg' %}" alt="Profile Picture">
                </div>
            </div>   
        </div>
    </div>
    {% endblock %}

portfolio/templates/portfolio/thanks.html
{% extends "portfolio/base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'portfolio/thanks.css' %}">

<div class="container p-4">
    <div class="col pt-3">
        <div class="row">
            <div class="col pt-3">
                <img src="{% static 'portfolio/images/thanks.jpg' %}" alt="thank you picture">
            </div>
            <div class="col-8 pt-3">
                <h1>Thank you for</h1>
                <h1>your comment!!</h1>
                <button type="button" class="btn btn-dark mt-5">
                    <a class="nav-link" href="{% url 'portfolio:index' %}">Return to Home Page</a>
                </button>
            </div>
        </div>
    </div>

{% endblock %}